<?php

declare(strict_types=1);

namespace Kinetis\Persistence\Contract;

use Traversable;

/**
 * A fully-buffered result set: iterable rows (associative arrays), plus
 * the metadata the query builder and application code actually consume.
 *
 * Buffering is part of the contract, not an implementation detail — a
 * consumer may stop iterating at any point with nothing left to drain or
 * dispose, and getRowCount() is always known. Result sets large enough
 * for streaming to matter don't belong on a per-request web driver.
 *
 * @extends Traversable<int, array<string, mixed>>
 */
interface SqlResult extends Traversable
{
    /**
     * Returns the next unconsumed row, or null once exhausted. Iteration
     * via foreach and fetchRow() share no cursor — foreach always yields
     * the full set.
     *
     * @return array<string, mixed>|null
     */
    public function fetchRow(): ?array;

    /**
     * Row count for a SELECT; affected-row count for DML; null when the
     * driver can't tell.
     */
    public function getRowCount(): ?int;

    public function getColumnCount(): ?int;

    /**
     * The auto-increment id generated by an INSERT, when the backend
     * reports one (MySQL). Null otherwise — Postgres reports generated
     * keys via RETURNING, not out-of-band.
     */
    public function getLastInsertId(): ?int;
}
