<?php

declare(strict_types=1);

namespace Kinetis\Persistence\Driver;

use Kinetis\Persistence\Exception\UnexpectedInsertIdException;

/**
 * Normalizes a raw MySQL-reported last-insert-id value — mysqli's own
 * $insert_id (documented to return int for a value within PHP's native
 * integer range, string once it exceeds it) or PDO::lastInsertId()'s
 * string|false — into the canonical int|string|null shape
 * {@see \Kinetis\Persistence\Contract\SqlResult::getLastInsertId()}
 * promises. Shared by MysqliAsyncClient and PdoMysqlClient so neither
 * can apply a different rule than the other.
 *
 * The common case — every ordinary AUTO_INCREMENT id — comes back as a
 * real int, exactly what every existing caller already expects.
 * UNSIGNED BIGINT allows values up to MYSQL_BIGINT_UNSIGNED_MAX, past
 * PHP_INT_MAX (9223372036854775807 on a 64-bit build): a value in that
 * range is preserved as its own canonical decimal string instead, never
 * coerced through a lossy (int) cast — confirmed directly, not assumed,
 * that such a cast silently saturates to PHP_INT_MAX rather than
 * reporting the real generated id, which an application could then use
 * to read or write the wrong row entirely. A value that cannot possibly
 * be a real MySQL-generated id at all — negative, non-numeric, or past
 * UNSIGNED BIGINT's own ceiling, the widest integer column type this is
 * ever normalizing a value from — is rejected rather than silently
 * passed through or discarded, since either would push a broken backend
 * invariant into application code disguised as valid.
 */
final class MysqlInsertId
{
    /** The real ceiling of MySQL's widest integer column type — nothing this helper normalizes can legitimately exceed it. */
    private const string MYSQL_BIGINT_UNSIGNED_MAX = '18446744073709551615';

    /**
     * @param int|string|false|null $raw
     *
     * @throws UnexpectedInsertIdException when $raw cannot possibly be
     *     a real MySQL-generated id: negative, non-numeric, or past
     *     UNSIGNED BIGINT's own ceiling. The contract this returns
     *     promises only ever an int or a canonical decimal string, so a
     *     value with no honest way to fit either shape is rejected
     *     rather than passed through as if it were a real id.
     */
    public static function normalize(int|string|false|null $raw): int|string|null
    {
        if ($raw === false || $raw === null || $raw === '') {
            return null;
        }

        if (is_int($raw)) {
            if ($raw < 0) {
                throw UnexpectedInsertIdException::forMalformedValue();
            }

            // 0 is MySQL's own "no id was generated by this statement"
            // signal (AUTO_INCREMENT never starts there), the same
            // meaning null already carries on this interface.
            return $raw !== 0 ? $raw : null;
        }

        if (!preg_match('/^[0-9]+$/', $raw)) {
            throw UnexpectedInsertIdException::forMalformedValue();
        }

        // Leading zeros are stripped before any length/value comparison
        // — a value like "000...0001" must be recognized as the small
        // number 1, not treated as exceeding PHP_INT_MAX purely because
        // its character count does. An all-zero string of any length
        // canonicalizes to the empty string here, meaning no generated
        // id — the same meaning the bare string "0" already carries.
        $canonical = ltrim($raw, '0');

        if ($canonical === '') {
            return null;
        }

        if (self::fitsWithinCeiling($canonical, (string) PHP_INT_MAX)) {
            return (int) $canonical;
        }

        if (self::fitsWithinCeiling($canonical, self::MYSQL_BIGINT_UNSIGNED_MAX)) {
            return $canonical;
        }

        // Past UNSIGNED BIGINT's own ceiling — not representable by the
        // column type this value is documented to come from, so this
        // cannot be a real generated id regardless of how it was
        // reported.
        throw UnexpectedInsertIdException::forMalformedValue();
    }

    /**
     * Digit-count first, then strcmp() on same-length strings —
     * strcmp() is a pure byte-wise comparison, never PHP's own
     * numeric-string coercion a bare <= would invoke for two
     * numeric-looking strings: PHP_INT_MAX and PHP_INT_MAX+1 are both
     * 19 digits, so the exact boundary this exists to get right depends
     * on this same-length comparison, and it is deliberately never left
     * to an operator whose behavior here depends on PHP's own
     * numeric-string detection rather than the coercion-free comparison
     * this class is meant to guarantee. $value is assumed already
     * canonicalized (no leading zeros) by the caller.
     */
    private static function fitsWithinCeiling(string $value, string $ceiling): bool
    {
        return \strlen($value) < \strlen($ceiling)
            || (\strlen($value) === \strlen($ceiling) && \strcmp($value, $ceiling) <= 0);
    }
}
